### ISSUE TITLE
Clone added Two items per one click

### ISSUE THREAD

**Issue by sakthiemail** [yapapaya/jquery-cloneya#21]
When I add one items, it added two items.
Can you check  the following example?
 http://jsfiddle.net/f6yLw8ch/13/

Thanks

**Comment by blaskxx** [comment]
how you delimit the times of deleting? with the original example it delete me all the form

**Comment by yapapaya** [comment]
@blaskxx Please create a separate ticket. We won't help you in this one.

**Comment by yapapaya** [comment]
@sakthiemail This is happening because cloneya is not yet equipped to handle nesting with the same class identifiers. So, you have a `.clone-inner` with a clone and delete button and inside that another `.clone-inner` with clone and delete buttons with the same class names.

This will be added in the future. However, for now, make sure all the nested levels have different class names, like your fiddle that I have modified: http://jsfiddle.net/f6yLw8ch/21/

**Comment by sakthiemail** [comment]
Thank you for your help. Thank you very much.

Thanks,
